# Generated by Django 6.0.1 on 2026-02-18 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveryAgent', '0002_initial'),
        ('superAdmin', '0001_initial'),
        ('vendor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagentapprovallog',
            name='admin_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_agent_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryagentapprovallog',
            name='delivery_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='deliveryAgent.deliveryprofile'),
        ),
        migrations.AddField(
            model_name='productapprovallog',
            name='admin_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productapprovallog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='vendor.product'),
        ),
        migrations.AddField(
            model_name='vendorapprovallog',
            name='admin_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorapprovallog',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='vendor.vendorprofile'),
        ),
    ]
