# Generated by Django 5.2 on 2026-02-17 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryAgent', '0002_initial'),
        ('superAdmin', '0001_initial'),
        ('user', '0001_initial'),
        ('vendor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.order'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='related_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.vendorprofile'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryagentapprovallog',
            name='admin_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_agent_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryagentapprovallog',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='deliveryAgent.deliveryagentprofile'),
        ),
        migrations.AddField(
            model_name='deliveryagentcommission',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='deliveryAgent.deliveryagentprofile'),
        ),
        migrations.AddField(
            model_name='deliveryagentcommission',
            name='commission_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superAdmin.commissionstructure'),
        ),
        migrations.AddField(
            model_name='deliveryagentcommission',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_commissions', to='user.order'),
        ),
        migrations.AddField(
            model_name='deliveryreport',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_reports', to='deliveryAgent.deliveryagentprofile'),
        ),
        migrations.AddField(
            model_name='disputeresolution',
            name='admin_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_resolutions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disputeresolution',
            name='dispute',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='user.dispute'),
        ),
        migrations.AddField(
            model_name='productapprovallog',
            name='admin_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productapprovallog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='vendor.product'),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_reports', to='vendor.vendorprofile'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_config_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorapprovallog',
            name='admin_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorapprovallog',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='vendor.vendorprofile'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['activity_type', '-created_at'], name='superAdmin__activit_6fa825_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-created_at'], name='superAdmin__user_id_8ca08c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deliveryreport',
            unique_together={('agent', 'date')},
        ),
    ]
