# Generated by Django 6.0.2 on 2026-02-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superAdmin', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productapprovallog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vendorapprovallog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
