# Generated by Django 6.0.1 on 2026-02-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('scooter', 'Scooter'), ('car', 'Car'), ('van', 'Van'), ('truck', 'Truck')], max_length=20)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('driving_license_number', models.CharField(max_length=50)),
                ('dl_image', models.FileField(blank=True, null=True, upload_to='delivery_docs/license/')),
                ('bank_holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_ifsc_code', models.CharField(blank=True, max_length=11, null=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=10, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('vendor_address', models.TextField()),
                ('delivery_address', models.TextField()),
                ('earning', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_ROUTE', 'On Route'), ('DELIVERED', 'Delivered')], default='AVAILABLE', max_length=10)),
            ],
        ),
    ]
