# Generated by Django 5.2 on 2026-02-17 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryAgent', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_agent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryagentperformance',
            name='agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='deliveryAgent.deliveryagentprofile'),
        ),
        migrations.AddField(
            model_name='deliveryagentwallet',
            name='agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='deliveryAgent.deliveryagentprofile'),
        ),
        migrations.AddField(
            model_name='deliveryagenttransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='deliveryAgent.deliveryagentwallet'),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_assignments', to='deliveryAgent.deliveryagentprofile'),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_assignment', to='user.order'),
        ),
        migrations.AddField(
            model_name='deliverycommission',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_commissions', to='deliveryAgent.deliveryagentprofile'),
        ),
        migrations.AddField(
            model_name='deliverycommission',
            name='delivery_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission', to='deliveryAgent.deliveryassignment'),
        ),
        migrations.AddField(
            model_name='deliverydailystats',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='deliveryAgent.deliveryagentprofile'),
        ),
        migrations.AddField(
            model_name='deliveryfeedback',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_received', to='deliveryAgent.deliveryagentprofile'),
        ),
        migrations.AddField(
            model_name='deliveryfeedback',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryfeedback',
            name='delivery_assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='deliveryAgent.deliveryassignment'),
        ),
        migrations.AddField(
            model_name='deliveryincentive',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to='deliveryAgent.deliveryagentprofile'),
        ),
        migrations.AddField(
            model_name='deliverypayment',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='deliveryAgent.deliveryagentprofile'),
        ),
        migrations.AddField(
            model_name='deliverypayment',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_payments_processed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverycommission',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission', to='deliveryAgent.deliverypayment'),
        ),
        migrations.AddField(
            model_name='deliverytracking',
            name='delivery_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='deliveryAgent.deliveryassignment'),
        ),
        migrations.AddIndex(
            model_name='deliveryagentprofile',
            index=models.Index(fields=['approval_status'], name='deliveryAge_approva_f1dd83_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryagentprofile',
            index=models.Index(fields=['availability_status'], name='deliveryAge_availab_ca7ed5_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryagentprofile',
            index=models.Index(fields=['is_blocked'], name='deliveryAge_is_bloc_5825b8_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryagentprofile',
            index=models.Index(fields=['-created_at'], name='deliveryAge_created_c3518b_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['agent', 'status'], name='deliveryAge_agent_i_85ffb0_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['order'], name='deliveryAge_order_i_47da70_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['-assigned_at'], name='deliveryAge_assigne_770d22_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverydailystats',
            index=models.Index(fields=['agent', '-date'], name='deliveryAge_agent_i_c546c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliverydailystats',
            constraint=models.UniqueConstraint(fields=('agent', 'date'), name='unique_agent_daily_stats'),
        ),
        migrations.AddIndex(
            model_name='deliveryfeedback',
            index=models.Index(fields=['agent'], name='deliveryAge_agent_i_ba85b8_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryfeedback',
            index=models.Index(fields=['customer'], name='deliveryAge_custome_e241f3_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverypayment',
            index=models.Index(fields=['agent', 'status'], name='deliveryAge_agent_i_a28b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverypayment',
            index=models.Index(fields=['-created_at'], name='deliveryAge_created_84c6ab_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverycommission',
            index=models.Index(fields=['agent', 'status'], name='deliveryAge_agent_i_98a6ec_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverycommission',
            index=models.Index(fields=['-created_at'], name='deliveryAge_created_9cfac1_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverytracking',
            index=models.Index(fields=['delivery_assignment', '-tracked_at'], name='deliveryAge_deliver_a76538_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverytracking',
            index=models.Index(fields=['-tracked_at'], name='deliveryAge_tracked_f9aa7e_idx'),
        ),
    ]
